---
- name: INSTALL | Signal
  tags:
    - install
  block:
    - name: INSTALL | Ensure signal is in apt keyring
      become: True
      ansible.builtin.apt_key:
        url: https://updates.signal.org/desktop/apt/keys.asc
        keyring: /usr/share/keyrings/signal-desktop-keyring.gpg
        state: present

    - name: INSTALL | Ensure signal is enabled in apt sources
      become: True
      notify: Update apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main"
        state: present

    - name: INSTALL | Update apt repository if needed
      ansible.builtin.meta: flush_handlers

    - name: INSTALL | Ensure signal is installed
      become: True
      ansible.builtin.apt:
        name: signal-desktop
        state: present
